Hairdressers_Azure/Controllers/AppointmentsController.cs
using Azure.Security.KeyVault.Secrets;
using CutAndGo.Models;
using Hairdressers_Azure.Filters;
using Hairdressers_Azure.Helpers;
using Hairdressers_Azure.Models;
using Hairdressers_Azure.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Security.Claims;

namespace Hairdressers_Azure.Controllers {
    public class AppointmentsController : Controller {
        
        private ServiceCutAndGo service;
        private SecretClient secretClient;

        public AppointmentsController(ServiceCutAndGo service, SecretClient secretClient) {
            this.service = service;
            this.secretClient = secretClient;
        }

        /*
         *  Recibiremos un identificador de peluquería (hairdresser_id) para determinar la solicitud de datos 
         *  que se le debe pasar al calendario (citas de una peluquería o de un usuario). Si no se añade un id
         *  de peluquería se entiende que se solicitan datos de citas de un usuario.
         *  
         *  En el caso de solicitar los datos de las citas de una peluquería, será necesario comprobar el rol
         *  de dicho usuario y su relación con dicha peluquería. (En futuras versiones se podría implementar
         *  en caché un validador para no recuperar en varias ocasiones la validación de la relación user-hairdresser)
         */

        [AuthorizeUsers]
        public async Task<IActionResult> Appointments(int? hairdresserId) {
            List<Appointment> appointments;
            int user_id = int.Parse(HttpContext.User.FindFirstValue("ID"));

            bool administrator_privileges; // Administrador de la peluquería
            string bussines_hours = "";
            bool hairdresser_view = false; // Vista de una única peluquería

            Hairdresser? hairdresser = null;
            List<Service>? services = null;

            if (hairdresserId != null) { // ¿Qué datos de citas queremos? ¿De usuario o de peluquería?

                hairdresser_view = true;
                if (HttpContext.User.FindFirst(ClaimTypes.Role).Value == "ADMIN") {
                    administrator_privileges = await this.service.AdminExistAsync(hairdresserId.Value, user_id);
                } else {
                    administrator_privileges = false;
                }

                // Recuperamos la peluquería
                hairdresser = await this.service.FindHairdresserAsync(hairdresserId.Value);

                // Listamos su horario activo para fijarlo como horario laboral
                List<Schedule_Row> schedule_rows = await this.service.GetActiveScheduleRowsAsync(hairdresserId.Value);
                bussines_hours = HelperCalendar.GetBussinesHours(schedule_rows);

                // Listamos los servicios de la peluquería
                services = await this.service.GetServicesByHairdresserAsync(hairdresserId.Value);

                // Listamos las citas de la peluquería
                appointments = await this.service.GetAppointmentsByHairdresserAsync(hairdresserId.Value);

            } else { // Se solicitan datos de citas de Usuario
                administrator_privileges = true;
                appointments = await this.service.GetAppointmentsByUserAsync(user_id);
            }

            // La lista recuperada es transformada y enviada a la vista para su representación
            List<object> appointments_json = await GenerateInfoCalendar(appointments, administrator_privileges, user_id);
            ViewData["HAIRDRESSER"] = hairdresser;
            ViewData["SERVICES"] = services != null && services.Count > 0 ? HelperJson.SerializeObject(services) : null;
            ViewData["BUSSINESS_HOURS"] = bussines_hours;
            ViewData["JSON_APPOINTMENTS"] = HelperJson.SerializeObject(appointments_json);
            ViewData["USER"] = await this.service.FindUserAsync(user_id);
            TempData["ADMIN_PRIV"] = administrator_privileges;
            TempData["HAIRDRESSER_VIEW"] = hairdresser_view;
            return View();
        }

        [HttpPost]
        [AuthorizeUsers]
        public async Task<IActionResult> CreateAppointment(string mydata) {
            GetCalendarAppointment appointment = JsonConvert.DeserializeObject<GetCalendarAppointment>(mydata);

            // Creación de la cita y recogida de servicios
            int appointment_id = await this.service.InsertAppointmentAsync(appointment.user_id, appointment.hairdresser_id, appointment.date, appointment.time);

            List<string> services = new List<string>();
            decimal full_cost_services = 0;
            foreach (int service_id in appointment.services) {
                await this.service.InsertAppointmentServiceAsync(appointment_id, service_id);
                Service service = await this.service.FindServiceAsync(service_id);
                services.Add(service.Name);
                full_cost_services += service.Price;
            }

            // Recogida del resto de datos para el email
            List<string> emails = await this.service.GetHairdresserEmailsAsync(appointment.hairdresser_id);

            string user_name = HttpContext.User.Identity.Name + " " + HttpContext.User.FindFirst("LAST_NAME").Value;
            string user_email = HttpContext.User.FindFirst("EMAIL").Value;

            string app_date = appointment.date.ToString("dd/MM/yyyy");
            string app_time = appointment.time.Hours.ToString().PadLeft(2, '0') + ":" + appointment.time.Minutes.ToString().PadLeft(2, '0');

            // Envío del correo de confirmación
            HelperEmailService sender = new HelperEmailService(this.secretClient);
            Hairdresser hairdresser = await this.service.FindHairdresserAsync(appointment.hairdresser_id);
            await sender.SendTemplateRequestAppointment(emails, user_name, user_email, app_date, app_time, services,
                                                        full_cost_services, hairdresser.Token, hairdresser.HairdresserId, appointment_id);

            return Json("/Appointments/Appointments?hairdresserId=" + appointment.hairdresser_id);
        }

        [AuthorizeUsers]
        public async Task<IActionResult> AppointmentConfirm(string token, int hid, int apid, bool redirect = false) {
            // Obtener los valores desde TempData
            token = (token != null) ? token : TempData["token"] as string;
            hid = (hid != 0) ? hid : Convert.ToInt32(TempData["hid"]);
            apid = (apid != 0) ? apid : Convert.ToInt32(TempData["apid"]);

            bool verification = await this.service.HairdresserValidateTokenAsync(hid, token);
            if (verification) {
                Appointment? appointment = await this.service.FindAppoinmentAsync(apid);
                if (appointment != null) {
                    await this.service.ApproveAppointmentAsync(apid);
                    User? user = await this.service.FindUserAsync(appointment.UserId);

                    HelperEmailService sender = new HelperEmailService(this.secretClient);
                    string app_date = appointment.Date.ToString("dd/MM/yyyy");
                    string app_time = appointment.Time.Hours.ToString().PadLeft(2, '0') + ":" + appointment.Time.Minutes.ToString().PadLeft(2, '0');
                    await sender.SendConfirmationAppointment(apid, user.UserId, user.Email, user.Name + " " + user.LastName, app_date, app_time);

                    ViewData["USER"] = user;
                    ViewData["APPOINTMENT"] = appointment;
                    ViewData["RESPONSE"] = 1; // Credenciales correctas, solicitud aprobada
                } else { // Cita no encontrada (Posible borrado de cita)
                    ViewData["RESPONSE"] = 2;
                }
            } else {
                ViewData["RESPONSE"] = 3; // No tiene permisos, solicitud denegada
            }

            return redirect ? Json("OK") : View();
        }

        [HttpPost]
        [AuthorizeUsers]
        public async Task<IActionResult> DeleteAppointment(string idAppoinment, string hairdresser_id) {
            await this.service.DeleteAppointmentAsync(int.Parse(idAppoinment));
            return Json("/Appointments/Appointments?hairdresserId=" + hairdresser_id);
        }

        [AuthorizeUsers]
        public IActionResult SelectAppointments() {
            return View();
        }

        private async Task<List<object>> GenerateInfoCalendar(List<Appointment> appointments, bool superUser, int user_id) {
            List<object> appointments_json = new List<object>();
            foreach (Appointment app in appointments) { // Recorremos las citas encontradas en la peluquería
                bool user_permission = app.UserId == user_id; // Si son datos de mis propias citas si que puedo verlas

                User? user = superUser || user_permission ? await this.service.FindUserAsync(app.UserId) : null;
                List<Service> services = await this.service.GetServicesByAppointmentAsync(app.AppointmentId);

                int timeAprox = GetMinutesByAppointment(services);
                string price = superUser || user_permission ? GetTotalPriceByAppointment(services) : "";
                string userName = (superUser || user_permission) && user != null ? user.Name : "CITA";
                string date = app.Date.ToString("yyyy-MM-ddT");

                dynamic services_json = new JObject();
                if (superUser || user_permission) { // Solo los super usuarios pueden ver los servicios de las citas
                    int serviceCount = 0; // Enumeración de los servicios a realizar en la cita
                    foreach (Service service in services) {
                        serviceCount++;
                        string propertyName = $"service_{serviceCount}";
                        string finalValue = service.Name + " (" + service.Price + "€)";
                        services_json.Add(propertyName, finalValue);
                    }

Hairdressers_Azure/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hairdressers_Azure.Controllers {
    public class LandingController : Controller {

        public IActionResult Index() {
            return View();
        }

        public IActionResult Help() {
            return View();
        }

        public IActionResult PrivatePolicy() {
            return View();
        }

        public IActionResult UseTerms() {
            return View();
        }

    }
}

Hairdressers_Azure/Controllers/UserController.cs
using Azure.Security.KeyVault.Secrets;
using CutAndGo.Models;
using Hairdressers_Azure.Filters;
using Hairdressers_Azure.Helpers;
using Hairdressers_Azure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Azure;

namespace Hairdressers_Azure.Controllers {
    public class UserController : Controller {
        
        private ServiceCutAndGo service;
        private ServiceStorageBlobs serviceBlob;
        private readonly SecretClient secretClient;

        public UserController(ServiceCutAndGo service, SecretClient secretClient, ServiceStorageBlobs serviceBlob) {
            this.service = service;
            this.serviceBlob = serviceBlob;
            this.secretClient = secretClient;
        }

        [AuthorizeUsers]
        public async Task<IActionResult> ControlPanel() {
            int userId = int.Parse(HttpContext.User.FindFirst("ID").Value);
            ViewData["HAIRDRESSERS"] = await this.service.GetHairdressersByUserAsync(userId);
            return View();
        }

        [AuthorizeUsers]
        public async Task<IActionResult> SendValidateEmail() {
            int userId = int.Parse(HttpContext.User.FindFirst("ID").Value);
            string name = HttpContext.User.Identity.Name;
            string lastName = HttpContext.User.FindFirst("LAST_NAME").Value;
            string email = HttpContext.User.FindFirst("EMAIL").Value;
            string token = await this.service.GenerateToken() + userId;

            await service.UserAssignTokenAsync(userId, token);
            await new HelperEmailService(this.secretClient).SendTemplateVerificationEmailAsync(email, name + " " + lastName, token);
            return Json("OK");
        }

        public async Task<IActionResult> ValidateEmail(string token) {
            int user_id = int.Parse(token.Substring(50));
            int response  = await service.ValidateEmailAsync(user_id, token);

            ViewData["RESPONSE"] = (response == user_id) ? 1 : 2; /// 1: Usuario encontrado y validado | 2: Usuario encontrado pero no validado
            return View();
        }

        [AuthorizeUsers]
        public async Task<IActionResult> DeleteUser() {
            int userId = int.Parse(HttpContext.User.FindFirst("ID").Value);
            string user_image = HttpContext.User.FindFirst("IMAGE").Value;
            await this.serviceBlob.DeleteBlobAsync("users", user_image); // Eliminamos el antiguo Blob

            List<Hairdresser> hairdressers = await this.service.GetHairdressersByUserAsync(userId);
            foreach (Hairdresser removeHairdresser in hairdressers) {
                if (removeHairdresser != null && removeHairdresser.Image != null && removeHairdresser.Image != "") {
                    await this.serviceBlob.DeleteBlobAsync("hairdressers", removeHairdresser.Image); // Eliminamos el antiguo Blob
                }
            }

            await this.service.DeleteUserAsync(userId);
            return RedirectToAction("LogOut", "Managed");
        }
        
        [AuthorizeUsers]
        public async Task<IActionResult> UpdateUser() {
            User? user = await service.FindUserAsync(int.Parse(HttpContext.User.FindFirst("ID").Value));
            return View(user);
        }

        [AuthorizeUsers] [HttpPost]
        public async Task<IActionResult> UpdateUser(UserUpdates user, IFormFile file) {
            // Comprobamos si existe un nuevo email con los claims del usuario
            bool existe = false; // Por defecto el email no está duplicado y no se han registrado cambios
            if (HttpContext.User.FindFirst("EMAIL").Value != user.Email) {
                existe = await this.service.EmailExistAsync(user.Email); // Verificamos el email
            }

            if (user != null && !existe) { // Si el usuario ha sido encontrado y no existe duplicidad de email
                string? extension = (file == null) ? null : System.IO.Path.GetExtension(file.FileName);
                if (file != null) { // Si no se ha registrado una nueva imagen de usuario no se ejecuta cambio de Blob
                    User? oldUser = await this.service.FindUserAsync(user.UserId);
                    if (oldUser != null && oldUser.Image != null && oldUser.Image != "") { 
                        await this.serviceBlob.DeleteBlobAsync("users", oldUser.Image); // Eliminamos el antiguo Blob
                    }
                    // Insertamos el nuevo Blob
                    string blobName = "user_" + user.UserId + extension;
                    using (Stream stream = file.OpenReadStream()) {
                        await this.serviceBlob.UploadBlobAsync("users", blobName, stream);
                    }
                }
                // Actualizamos el usuario
                await this.service.UpdateUserAsync(user.UserId, user.Name, user.LastName, user.Phone, user.Email, extension);
            }
            return RedirectToAction("LogOut", "Managed", new { toLogIn = true });
        }

        [AuthorizeUsers]
        public async Task<IActionResult> UserHairdressers() {
            int userId = int.Parse(HttpContext.User.FindFirst("ID").Value);
            List<Hairdresser> hairdressers = await this.service.GetHairdressersByUserAsync(userId);
            return View(hairdressers);
        }

    }
}

Hairdressers_Azure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>

    @* ======== ESTILOS COMUNES EN LA APLICACIÓN ======== *@
    <link rel="stylesheet" href="~/css/common_styles/backgrounds.css" />
    <link rel="stylesheet" href="~/css/common_styles/colors.css" />
    <link rel="stylesheet" href="~/css/common_styles/common.css" />
    <link rel="stylesheet" href="~/css/common_styles/fonts.css" />
    <link rel="stylesheet" href="~/css/loading.css" />
    @* ================================================== *@

    @* =============== ESTILOS DEL LAYOUT =============== *@
    <link rel="stylesheet" href="~/css/layout_styles/header.css" />
    <link rel="stylesheet" href="~/css/layout_styles/footer.css" />
    @* ================================================== *@
    
    @* ============== ESTILOS DE LAS VISTAS ============= *@
    <link rel="stylesheet" href="~/css/landing.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="~/css/hairdresser.css" />
    <link rel="stylesheet" href="~/css/user_admin.css" />
    <link rel="stylesheet" href="~/css/services.css" />
    <link rel="stylesheet" href="~/css/suggestions.css" />
    <link rel="stylesheet" href="~/css/schedules.css" />
    <link rel="stylesheet" href="~/css/userHairdressers.css" />
    @* ================================================== *@

    @* ========== ESTILOS DE LOS HTML GENERADOS ========= *@
    <link rel="stylesheet" href="~/css/calendarSwal.css" />
    @* ================================================== *@

    @* ============================================= ICONOS ============================================ *@
    <link rel="icon" type="image/x-icon" href="~/images/logos/Barber_logo_small_white.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

    <script src="~/js/jquery-3.6.3.min.js"></script>
    <script src="~/js/index.global.min.js"></script>
</head>
<body onunload="eliminarDatos()">
    <div class="loadingContainer" style="display: none;">
        <h1 class="loadingText">
            Cargando
            <div class="dots">
                <span class="dot z"></span>
                <span class="dot f"></span>
                <span class="dot s"></span>
                <span class="dot t">
                    <span class="dot l"></span>
                </span>
            </div>
        </h1>

        <a asp-controller="Landing" asp-action="Index" class="loadingBack">
            Forzar la vuelta a la página de inicio
        </a>
    </div>

    <header>
        <div id="navbar_container" class="shadow">
            <div id="navbar_container_logo">
                <img id="navbar_logo" src="~/images/logos/Barber_logo_medium_transparent.png"/>
            </div>
            <div id="navbar_container_buttons">
                <ul class="navbar_list rel_center">
                    <partial name="_MenuNavLink" />
                </ul>
            </div>
            <div id="navbar_container_login">
                <ul class="navbar_list rel_center">
                    <li>
                        <button id="navbar_user" class="navbar_list_item">
                            <img src="@Context.Session.GetString("IMAGE_USER")" class="navbar_user_image" />
                        </button>
                        <ul id="navbar_float">
                            <partial name="_MenuLogin" />
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    @RenderBody()

    <footer class="footer">
        <div class="footer__addr">
            <h1 class="footer__logo">Cut&Go S.A.</h1>
            <h2>Contáctanos</h2>
            <address>
                C. de Pío Felipe, 12, 28038 Madrid<br>
                cutandgo.app@gmail.com<br>
                <a class="footer__btn" href="mailto:cutandgo.app@gmail.com">Enviar email</a>
            </address>
        </div>

        <ul class="footer__nav">
            <li class="nav__item">
                <h2 class="nav__title">Clientes</h2>
                <ul class="nav__ul">
                    <li><a asp-controller="User" asp-action="ControlPanel">Panel de control</a></li>
                    <li><a asp-controller="Appointments" asp-action="Appointments">Mis citas</a></li>
                </ul>
            </li>
            <li class="nav__item">
                <h2 class="nav__title">Legal</h2>
                <ul class="nav__ul">
                    <li><a asp-controller="Landing" asp-action="PrivatePolicy">Política de privacidad</a></li>
                    <li><a asp-controller="Landing" asp-action="UseTerms">Términos de uso</a></li>
                </ul>
            </li>
        </ul>

        <div class="legal">
            <p>&copy; 2023 Cut&Go. Todos los derechos reservados.</p>
        </div>
    </footer>

    @if (IsSectionDefined("user_script")) { @RenderSection("user_script", false) }
    @if (IsSectionDefined("registrer_script")) { @RenderSection("registrer_script", false) }
    @if (IsSectionDefined("login_script")) { @RenderSection("login_script", false) }
    @if (IsSectionDefined("hairdresser_script")) { @RenderSection("hairdresser_script", false) }
    @if (IsSectionDefined("createhairdresser_script")) { @RenderSection("createhairdresser_script", false) }
    @if (IsSectionDefined("updateSchedule_script")) { @RenderSection("updateSchedule_script", false) }
    @if (IsSectionDefined("calendar_script")) { @RenderSection("calendar_script", false) }
    @if (IsSectionDefined("search_script")) { @RenderSection("search_script", false) }
    @if (IsSectionDefined("service_script")) { @RenderSection("service_script", false) }
    @if (IsSectionDefined("user_update_script")) { @RenderSection("user_update_script", false) }
    @if (IsSectionDefined("userHairdresser")) { @RenderSection("userHairdresser", false) }
    
    <script>
        $(document).ready(function() {
            $("#navbar_float").hide();

            $("#navbar_user").click(function() {
                  $("#navbar_float").slideToggle();
            });

            $(document).click(function (event) {
                if (!$(event.target).closest("#navbar_user").length) {
                    $("#navbar_float").slideUp();
                }
            });
        });

        function animate(element, className) {
            element.addClass(className);
            setTimeout(() => {
                element.removeClass(className);
                setTimeout(() => {
                    animate(element, className);
                }, 200);
            }, 1000);
        }

        function eliminarDatos() {
            $.ajax({
                url: "/Managed/DeleteSessionAndCookies",
                type: "POST",
                async: false
            });
        }
    </script>
    <script src="~/js/sweetalert2.all.min.js"></script>
</body>
</html>

Hairdressers_Azure/Views/Shared/_MenuLogin.cshtml
@if (Context.User.Identity.IsAuthenticated == true) {
    <li>
        <a asp-controller="User" asp-action="ControlPanel" class="navbar_float_items" id="navbar_float_first">
            Panel de control
        </a>
    </li>
    <li>
        <a asp-controller="User" asp-action="UserHairdressers" class="navbar_float_items">
            Mis peluquerías
        </a>
    </li>
    <li>
        <a asp-controller="Managed" asp-action="LogOut" class="navbar_float_items" id="navbar_float_last">
            Cerrar sesión
        </a>
    </li>
} else {
    <li>
        <a asp-controller="User" asp-action="ControlPanel" class="navbar_float_items" id="navbar_float_first">
            Iniciar Sesión
        </a>
    </li>
    <li>
        <a asp-controller="Managed" asp-action="Registrer" class="navbar_float_items" id="navbar_float_last">
            Registrarme
        </a>
    </li>
}

Hairdressers_Azure/Views/Shared/_MenuNavLink.cshtml
<li>
    <a asp-controller="Landing" asp-action="Index" class="navbar_list_item">Home</a>
</li>
<li>
    <a asp-controller="Appointments" asp-action="SelectAppointments" class="navbar_list_item">Citas</a>
</li>
<li>
    <a asp-controller="Landing" asp-action="Help" class="navbar_list_item">Help</a>
</li>