Hairdressers_Azure/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hairdressers_Azure.Controllers {
    public class LandingController : Controller {

        public IActionResult Index() {
            return View();
        }

        public IActionResult Help() {
            return View();
        }

        public IActionResult PrivatePolicy() {
            return View();
        }

        public IActionResult UseTerms() {
            return View();
        }

    }
}

Hairdressers_Azure/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using CutAndGo.Models;
using System.Security.Claims;
using Hairdressers_Azure.Services;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using Azure.Storage.Blobs;
using Azure.Storage.Sas;

namespace Hairdressers_Azure.Controllers {
    public class ManagedController : Controller {
        
        private ServiceCutAndGo service;
        private ServiceStorageBlobs serviceBlob;

        public ManagedController(ServiceCutAndGo service, ServiceStorageBlobs serviceBlob) {
            this.service = service;
            this.serviceBlob = serviceBlob;
        }

        public IActionResult LogIn() {
            return View();
        }

        private async Task<string> ExtractAndSaveTokenAsync(string responseToken) {
            dynamic responseObject = JsonConvert.DeserializeObject(responseToken);
            string token = responseObject.response;
            HttpContext.Session.SetString("TOKEN", token);
            return token;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn(string email, string password) {
            string responseToken = await this.service.LogInAsync(email, password);

            if (responseToken != null) {
                string token = await this.ExtractAndSaveTokenAsync(responseToken);

                // EXTRACCIÓN DEL USUARIO DE DICHO TOKEN
                JwtSecurityTokenHandler tokenHandler = new JwtSecurityTokenHandler();
                JwtSecurityToken parsedToken = tokenHandler.ReadJwtToken(token);

                IEnumerable<Claim> claims = parsedToken.Claims;
                Claim userDataClaim = claims.FirstOrDefault(c => c.Type == "UserData");
                User? user = null;
                if (userDataClaim != null) {
                    string userDataJson = userDataClaim.Value;
                    user = JsonConvert.DeserializeObject<User?>(userDataJson);
                }

                if (user != null) { // Usuario encontrado, credenciales correctas
                    await SignInUser(user); // Ejecutamos el LogIn del Usuario

                    if (user.Image != null && user.Image != "") {
                        await ChargeImage(user.Image); // Cargamos la imagen del usuario para no sobrecargar el storage a peticiones
                    }

                    string controller = TempData["controller"].ToString();
                    string action = TempData["action"].ToString();

                    return RedirectToAction(action, controller);
                } else {
                    ViewData["VERIFICATION"] = "Credenciales incorrectas";
                    return View();
                }

            } else {
                ViewData["VERIFICATION"] = "Credenciales incorrectas";
                return View();
            }
        }

        public async Task<IActionResult> LogOut(bool toLogIn = false) {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            HttpContext.Session.Remove("IMAGE_USER");
            return (toLogIn) ? RedirectToAction("ControlPanel", "User") : RedirectToAction("Index", "Landing");
        }

        public IActionResult DeleteSessionAndCookies() {
            // Eliminar la sesión
            HttpContext.Session.Clear();

            // Eliminar las cookies
            foreach (var cookie in Request.Cookies.Keys) {
                Response.Cookies.Delete(cookie);
            }

            return Json("OK");
        }


        public IActionResult Registrer() {
            return View();
        }

        [HttpPost] [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registrer(string Password, string Name, string LastName, string Phone, string Email, IFormFile file) {
            // Si no se carga imagen de usuario se envía null. La BBDD / API insertará una cadena vacía en su lugar y no se guardará foto
            string? extension = (file == null) ? null : System.IO.Path.GetExtension(file.FileName);
            User? user = await this.service.InsertUserAsync(Name, LastName, Phone, Email, Password, extension);

            if (file != null) { // Si no se ha registrado una imagen de usuario no se ejecuta ningún guardado de BLOB
                string blobName = "user_" + user.UserId + extension;
                using (Stream stream = file.OpenReadStream()) {
                    await this.serviceBlob.UploadBlobAsync("users", blobName, stream);
                }
            }

            if (user != null) {
                string responseToken = await this.service.LogInAsync(Email, Password);
                await this.ExtractAndSaveTokenAsync(responseToken); // Extracción del Token y almacenamiento en Session
                await SignInUser(user); // Ejecutamos el LogIn del nuevo Usuario registrado
                if (file != null) { // No podemos cargar una imagen si no ha registrado una
                    await ChargeImage(user.Image); // Cargamos la imagen del usuario para no sobrecargar el storage a peticiones
                }
                return RedirectToAction("ControlPanel", "User"); // Le enviamos al Panel de Control
            }
            return View(""); // Si el registro falla, se mantiene la vista
        }

        public IActionResult AccesoDenegado() {
            return View();
        }

        public IActionResult Error() {
            return View();
        }

        private async Task ChargeImage(string blobName) {
            if (blobName != null && blobName != "") {
                BlobContainerClient blobContainerClient = await this.serviceBlob.GetContainerAsync("users");
                BlobClient blobClient = blobContainerClient.GetBlobClient(blobName);

                BlobSasBuilder sasBuilder = new BlobSasBuilder() {
                    BlobContainerName = "users",
                    BlobName = blobName,
                    Resource = "b",
                    StartsOn = DateTimeOffset.UtcNow,
                    ExpiresOn = DateTime.UtcNow.AddHours(1),
                };

                sasBuilder.SetPermissions(BlobSasPermissions.Read);
                var uri = blobClient.GenerateSasUri(sasBuilder);
                HttpContext.Session.SetString("IMAGE_USER", uri.ToString());
            }
        }

        private async Task SignInUser(User user) {
            ClaimsIdentity identity = new ClaimsIdentity(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    ClaimTypes.Name, ClaimTypes.Role
            );

            string admin = await this.service.UserIsAdminAsync(user.UserId) ? "ADMIN" : "CLIENT";

            Claim claimUserID = new Claim("ID", user.UserId.ToString());
            Claim claimUserName = new Claim(ClaimTypes.Name, user.Name);
            Claim claimUserLastName = new Claim("LAST_NAME", user.LastName);
            Claim claimUserEmail = new Claim("EMAIL", user.Email);
            Claim claimUserEmailConfirmed = new Claim("EMAIL_CONFIRMED", user.EmailConfirmed.ToString());
            Claim claimUserPhone = new Claim("PHONE", user.Phone);
            Claim claimUserImage = new Claim("IMAGE", user.Image);
            Claim claimUserRole = new Claim(ClaimTypes.Role, admin);

            identity.AddClaim(claimUserID);
            identity.AddClaim(claimUserName);
            identity.AddClaim(claimUserLastName);
            identity.AddClaim(claimUserEmail);
            identity.AddClaim(claimUserEmailConfirmed);
            identity.AddClaim(claimUserPhone);
            identity.AddClaim(claimUserImage);
            identity.AddClaim(claimUserRole);

            ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                userPrincipal
            );
        }

    }
}

Hairdressers_Azure/Views/Landing/Help.cshtml
@{
    ViewData["TITLE"] = "C&G: Confirmación de la cita";
}

<div class="background_base bkg_003"></div>
<h1 class="commonTitle">PÁGINA EN CONSTRUCCIÓN - SENTIMOS LAS MOLESTIAS</h1>

Hairdressers_Azure/Views/Landing/Index.cshtml
@{
    ViewData["Title"] = "Cut&Go: Home";
}

<video autoplay muted loop id="bkg_video" poster="~/images/pictures/poster.jpg">
    <source src="~/movies/hairdresser_movie_6.mp4" type="video/mp4">
</video>
<div id="landing_content">
    <div id="sidetext">
        <h1 id="title_landing">
            <span class="text-shadow" style="color: rgb(65,80,115);">Cut</span>&<span class="text-shadow" style="color: rgb(156,72,81);">Go</span>
        </h1>
        <div id="description_content">
            <p>
                ¿Te gustaría poder reservar cita en tu peluquería favorita de forma rápida y sencilla? 
                ¿o gestionar la agenda de tu local con tan solo un par de clics? 
            </p>
            <p style="text-align: center; line-height: 3em;"><strong>Cut&Go te lo pone fácil.</strong></p>
            <p>
                Con nuestra plataforma, tus clientes podrán reservar citas en tu peluquería
                en cuestión de segundos. Podrás gestionar tu agenda de una forma eficiente y visual.
            </p> <br/>
            <p>
                Cut&Go es la <strong>solución perfecta</strong> para cualquier empresa o local del sector 
                de la estética que quiera mejorar su servicio al cliente y a la vez aumentar su visibilidad 
                en internet.<br/>Únete hoy a la red de peluquerías asociadas a Cut&Go y dale un impulso a tu negocio.
            </p>
            <a asp-controller="Managed" asp-action="Registrer">
                Unirme
            </a>
        </div>
    </div>
</div>
<div id="landing_aside">
    <h1>¿Tienes un negocio? ¡Mejora tu gestión con Cut&Go!</h1>
    <p>Ya son muchos los negocios que confían en nuestra plataforma para gestionar su flujo de trabajo.
       Además, podrás unirte a nuestras redes sociales y compartir tu contenido y tu trabajo con toda la comunidad</p>
    <img src="~/images/pictures/hairdresser_pics_6.jpg"/>
</div>

Hairdressers_Azure/Views/Landing/PrivatePolicy.cshtml
@{
    ViewData["Title"] = "Cut&Go: Política de privacidad";
}

<div class="background_base bkg_001"></div>
<div class="container_box legal_container">
    <h3>Política de Privacidad de Cut&Go</h3>
    <p>En Cut&Go, valoramos tu privacidad y nos comprometemos a proteger tus datos personales. Esta política de privacidad describe cómo recopilamos, utilizamos, almacenamos y protegemos la información que nos proporcionas al utilizar nuestra aplicación móvil o nuestro sitio web.</p><br/>
    
    <h4>Recopilación de información</h4> <br/>
    <p>Recopilamos información personal como tu nombre, dirección de correo electrónico, número de teléfono, dirección de la peluquería y otros datos relevantes para el uso de nuestros servicios. También podemos recopilar información sobre tus citas y transacciones realizadas a través de nuestra aplicación.</p><br/>
    
    <h4>Uso de la información</h4> <br/>
    <p>La información que recopilamos se utiliza para mejorar nuestros servicios y brindarte una experiencia de usuario más personalizada. También podemos utilizar tu información para enviarte correos electrónicos o notificaciones sobre promociones, actualizaciones y noticias relacionadas con Cut&Go.</p><br/>
    
    <h4>Compartir información</h4> <br/>
    <p>No vendemos ni compartimos tu información personal con terceros sin tu consentimiento. Podemos compartir tu información con proveedores de servicios de confianza que nos ayudan a ofrecer nuestros servicios. También podemos compartir tu información en caso de que sea requerido por la ley o por una orden judicial.</p><br/>
    
    <h4>Seguridad de la información</h4> <br/>
    <p>Tomamos medidas de seguridad técnicas y organizativas adecuadas para proteger tu información personal contra el acceso no autorizado, la divulgación, el uso indebido y la alteración. Sin embargo, ten en cuenta que ninguna transmisión de datos por Internet puede garantizar una seguridad absoluta.</p><br/>
    
    <h4>Cambios en la política de privacidad</h4> <br/>
    <p>Podemos actualizar esta política de privacidad de vez en cuando. Te recomendamos que revises periódicamente esta página para estar al tanto de los cambios. Si realizamos cambios significativos en nuestra política de privacidad, te lo notificaremos a través de nuestra aplicación o sitio web.</p><br/>
    
    <h4>Contacto</h4> <br/>
    <p>Si tienes alguna pregunta o inquietud sobre nuestra política de privacidad, contáctanos a través de nuestro correo electrónico: cutandgo.app@gmail.com.</p>
</div>

Hairdressers_Azure/Views/Landing/UseTerms.cshtml
@{
    ViewData["Title"] = "Cut&Go: Política de privacidad";
}

<div class="background_base bkg_001"></div>
<div class="container_box legal_container">
    <h3>Términos de Uso de Cut&Go</h3>
    <p>Bienvenido a Cut&Go, la aplicación móvil y sitio web que permite a los usuarios reservar citas en peluquerías. Al utilizar nuestros servicios, aceptas los siguientes términos y condiciones:</p><br />
    
    <h4>Uso de la aplicación</h4> <br />
    <p>Cut&Go proporciona una plataforma para que los usuarios reserven citas en peluquerías registradas en nuestra aplicación. No somos responsables de los servicios prestados por las peluquerías, ya que son empresas independientes. Tampoco nos hacemos responsables por cualquier pérdida o daño que puedas sufrir al utilizar nuestra aplicación o al reservar una cita en una peluquería.</p><br />
    
    <h4>Registro</h4> <br />
    <p>Para utilizar nuestros servicios, debes registrarte en nuestra aplicación proporcionando información precisa y completa. Al registrarte, aceptas recibir correos electrónicos y notificaciones de Cut&Go sobre tus citas, promociones y actualizaciones.</p><br />
    
    <h4>Reserva de citas</h4> <br />
    <p>La reserva de citas se realiza directamente con las peluquerías registradas en nuestra aplicación. Cut&Go no garantiza la disponibilidad de citas y no se hace responsable de cualquier cambio en la disponibilidad de citas realizadas a través de nuestra aplicación. Las cancelaciones y cambios de citas están sujetos a las políticas de cancelación de la peluquería correspondiente.</p><br />
    
    <h4>Propiedad intelectual</h4> <br />
    <p>Todos los derechos de propiedad intelectual relacionados con nuestra aplicación y sitio web son propiedad exclusiva de Cut&Go. No se te otorga ninguna licencia o derecho para utilizar ninguna marca registrada, logotipo o contenido de nuestra aplicación o sitio web.</p><br />
    
    <h4>Modificaciones</h4> <br />
    <p>Nos reservamos el derecho de modificar o actualizar estos términos de uso en cualquier momento. Si realizamos cambios significativos, te notificaremos a través de nuestra aplicación o sitio web. Al seguir utilizando nuestros servicios después de cualquier modificación, aceptas los términos actualizados.</p><br />
    
    <h4>Terminación</h4> <br />
    <p>Nos reservamos el derecho de cancelar tu cuenta y tu acceso a nuestra aplicación y sitio web en cualquier momento y por cualquier motivo sin previo aviso.</p><br />
    
    <h4>Contacto</h4> <br />
    <p>Si tienes alguna pregunta o inquietud sobre nuestros términos de uso, contáctanos a través de nuestro correo electrónico: cutandgo.app@gmail.com.</p>
</div>